[package]
name = "tableaux"
version = "0.1.0"
edition = "2024"

[features]
parse = ["winnow"]
default = ["parse"]

[dependencies]
anstyle = "1.0.10"
winnow = { version = "0.7.10", optional = true }

[workspace]
resolver = "3"
members = [
  ".",
  "playground",
]
